### PR TITLE
Citations: display count per each year below bar chart

### PR DESCRIPTION
**Pull request by ihnorton**
@ljod @zhangfanmark

### CODE REVIEW

**Comment by ihnorton** [comment]
Chrome isn't letting me paste a screenshot for some reason, so I went ahead and merged. I added the cite-per-year count below year as we discussed. I also updated the script used to generate the chart. Upstream has changed the script to generate a single bar per publication type. I think it looks better now, but we can go back to the other way if you don't like it.

http://dmri.slicer.org/citations/

**Comment by ljod** [comment]
Looks good to me thanks.
We have a new issue that there is some text saying parts of the citations are missing. This shows up in red color text so it looks bad. One option is for Fan to go through and complete the citations.

**Comment by ihnorton** [comment]
Oops, that's ugly. I could make it show up as `[...]` or something like that, so it doesn't look so bad.

I'll check what the previous behavior was too (probably just printed blank).

**Comment by ihnorton** [comment]
Ok, I changed it back to the previous display, which was showing 'NA' in gray for any missing field.

**Comment by ihnorton** [comment]
(to find missing items to fix in the future, just use ctrl-F and a space before and after NA: ` NA `)

**Comment by ljod** [comment]
Hi please check the labels: 2 conferences. What is "in collection?" If it's a conference we should edit the bibtex.

**Comment by ihnorton** [comment]
The legend labels come from the `@inproceedings`, `@article`, etc. tags in the bibtex file. The mapping from tag to label is here:

https://github.com/SlicerDMRI/slicerdmri.github.io/blob/4085d73168de507c1b4bb78f71e5c7f9ecd96c0f/citations/bib-list.js#L2699-L2713

The duplicate for "Conference" is because several different tags map to "Conference", but there is no aggregation done. I looked at the code a bit, and I think it would be simpler to just change the mapping so that each tag corresponds to a unique label.

> What is "in collection?"

Changed to "Book" in PR below.

For now, see PR: https://github.com/SlicerDMRI/slicerdmri.github.io/pull/9

(I also opened an issue in the original repository: https://github.com/vkaravir/bib-publication-list/issues/23)

**Pull request merged**
